name: Contract Verification WebHook

on:
  push:
  
  workflow_dispatch:
    inputs:
      consumer_branch:
        description: 'this will be the tag of the contract being uploaded, which should be verified'
        required: true
        default: 'staging'



jobs:
  contracts-verification:
    runs-on: ubuntu-latest
    env:
      PACT_BROKER_URL: https://usertesting.pactflow.io/

    steps:
      - uses: actions/checkout@v3

      - name: Shutdown Ubuntu MySQL (SUDO)
        run:  |
          sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it
          # sudo apt remove --auto-remove mysql-server
          # sudo apt purge --auto-remove mysql-server

      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '5.7'
      - run: mysql -uroot -h127.0.0.1 -e 'SELECT version()'

          
